version: '3.8'
## Reference: https://docs.docker.com/compose/networking/
services:
  backend:
    name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    deploy:
      replicas: 3  # Instances of the service
      restart_policy:
        condition: on-failure
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:3000"  # Load balancer port
    depends_on:
      - backend