name: ehr-frontend
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/frontend
    environment:
      VITE_API_URL: http://localhost:3000