name: ehr-services
services:
  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - shared-network

  frontend:
    container_name: frontend
    build:
      context: ../ehr-mapping
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - shared-network

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - shared-network

networks:
  shared-network:
    name: ehr-network