services:
  backend:
    volumes:
      - ../backend:/backend
      - /backend/node_modules
    environment:
      NODE_ENV: development
    command: npm run start:dev
    ports:
      - "3000:3000"

  frontend:
    volumes:
      - ../ehr-mapping:/frontend
      - /ehr-mapping/node_modules
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend
    command: npm run dev 
    ports:
      - "5173:5173"